// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAINt9LnurZbJwhYzC1HYMIVv3hF7egtF4',
    appId: '1:852036676932:web:0843b8069f77e21720bb11',
    messagingSenderId: '852036676932',
    projectId: 'data-producttivity-v1',
    authDomain: 'data-producttivity-v1.firebaseapp.com',
    storageBucket: 'data-producttivity-v1.appspot.com',
    measurementId: 'G-Y0D99EYQGF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-GT27csJuzsWrkgQgwVlz6HeBl2x8m90',
    appId: '1:852036676932:android:6c962ae9ce835c1320bb11',
    messagingSenderId: '852036676932',
    projectId: 'data-producttivity-v1',
    storageBucket: 'data-producttivity-v1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaL84xa99Or8lkKUJ9sdGJ39XFdfJnv2w',
    appId: '1:852036676932:ios:9e0883741108172e20bb11',
    messagingSenderId: '852036676932',
    projectId: 'data-producttivity-v1',
    storageBucket: 'data-producttivity-v1.appspot.com',
    iosBundleId: 'com.example.productivityApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAaL84xa99Or8lkKUJ9sdGJ39XFdfJnv2w',
    appId: '1:852036676932:ios:6933f42af21e008420bb11',
    messagingSenderId: '852036676932',
    projectId: 'data-producttivity-v1',
    storageBucket: 'data-producttivity-v1.appspot.com',
    iosBundleId: 'com.example.productivityApp.RunnerTests',
  );
}
